# Generated by Django 6.1 on 2026-08-26 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventopuerta',
            name='temperatura',
            field=models.FloatField(blank=True, help_text='Temperatura registrada (en °C)', null=True),
        ),
        migrations.AlterField(
            model_name='eventopuerta',
            name='confianza_promedio',
            field=models.FloatField(help_text='Nivel de confianza de la detección del modelo'),
        ),
    ]
