# Generated by Django 6.1 on 2026-08-25 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventoPuerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evento', models.CharField(default='puerta_abierta', max_length=50)),
                ('hora_apertura', models.DateTimeField()),
                ('hora_cierre', models.DateTimeField(blank=True, null=True)),
                ('duracion_segundos', models.FloatField(blank=True, null=True)),
                ('confianza_promedio', models.FloatField()),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='')),
                ('creado_el', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
